const data = {
  products: [
    {
      name: 'THE SANDMAN: OVERTURE',
      slug: 'the-sandman-overture',
      images: '/images/sandman.jpeg',
      category: 'Graphic Novel',
      price: 19.99,
      editor: 'Vertigo',
      authors: 'Neil Gaiman',
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description:
        'Twenty-five years after THE SANDMAN first changed the landscape of modern comics, Neil Gaiman’s legendary series is back! From the birth of a galaxy to the moment that Morpheus is captured, THE SANDMAN: OVERTURE features cameo appearances by fan-favorite characters such as the Corinthian, Merv Pumpkinhead and, of course, the Dream King’s siblings: Death, Desire, Despair, Delirium, Destruction and Destiny. This volume collects THE SANDMAN: OVERTURE #1-6 in its entirety, plus bonus material.',
    },
    {
      name: 'HARLEY QUINN #30',
      slug: 'harley-quinnharley30',
      images: '/images/quinn.jpeg',
      category: 'Comic-book',
      price: 3.99,
      editor: 'DCcomics',
      authors: '',
      rating: 3.2,
      numReviews: 1,
      countInStock: 70,
      description:
        'As Harley’s monthly series comes to an end, the world prepares for twice as much Harley when her new series debuts in August! And you’d better believe Harley’s burning the place down on the way out the door… FINAL ISSUE...you know, for now',
    },
    {
      name: 'DEADPOOL & TMFM #5',
      slug: 'deadpool-tmfm5',
      images: '/images/deadpool.jpeg',
      category: 'Comic-book',
      price: 0.99,
      editor: 'MARVEL',
      authors: 'Cullen Bunn, Iban Coello',
      rating: 3.6,
      numReviews: 1,
      countInStock: 70,
      description:
        'A new team means new rules! It`s now Domino`s Mercs for Money and she`s in charge! Sorry, Wade!',
    },
    {
      name: 'ABSOLUTE PREACHER VOL. 1',
      slug: 'absolute-preacher-vol-1',
      images: '/images/preacher.jpeg',
      category: 'Graphic Novel',
      price: 150.0,
      editor: 'Vertigo',
      authors: 'Garth Ennis, Steve Dillon',
      rating: 4.8,
      numReviews: 12,
      countInStock: 1,
      description:
        'PREACHER #1-26 are collected in this new Absolute edition! Merging with a bizarre force called Genesis, preacher Jesse Custer possesses the power of “The Word,” an ability to make people do whatever he utters! Joined by his gun-toting girlfriend Tulip and hard-drinking vampire Cassidy, Custer begins a violent and riotous journey across the country to find God.',
    },
    {
      name: 'HELLBLAZER BY GARTH ENNIS',
      slug: 'hellblazer-by-garth-ennis',
      images: '/images/hellblazer.png',
      category: 'Graphic Novel',
      price: 150.0,
      editor: 'Vertigo',
      authors: 'Garth Ennis',
      rating: 4.6,
      numReviews: 16,
      countInStock: 23,
      description:
        'Before PREACHER, Garth Ennis became a sensation with his acclaimed tales from HELLBLAZER—collected here in omnibus format! In these tales, John Constantine contracts cancer and makes a deal with the devil to save himself. Plus, Constantine encounters the king of vampires, fights fascists and takes a trip to the US—alongside the ghost of JFK. Collects HELLBLAZER #41-50, #52-83, #129-133, HELLBLAZER SPECIAL #1 and HEARTLAND #1.',
    },
    {
      name: 'THE PLANETARY OMNIBUS',
      slug: 'the-planetary-omnibus',
      images: '/images/planetary.jpeg',
      category: 'Graphic Novel',
      price: 75.0,
      editor: 'WildStorm',
      authors: 'Warren Ellis, John Cassaday',
      rating: 5.0,
      numReviews: 20,
      countInStock: 333,
      description:
        'Hailed as a timeless story that turned modern super hero conventions on their heads, PLANETARY stars an inter-dimensional peace-keeping force including Elijah Snow, Jakita Wagner, and The Drummer. Tasked with tracking down evidence of super-human activity, these mystery archaeologists uncover unknown paranormal secrets and histories, such as a World War II supercomputer that can access other universes, a ghostly spirit of vengeance, and a lost island of dying monsters. Now, the entire series is collected in hardcover, including PLANETARY #1-27, PLANETARY/BATMAN #1, PLANETARY/JLA #1 and PLANETARY/AUTHORITY #1.',
    },
    {
      name: 'THE BOYS #3',
      slug: 'the-boys3',
      images: '/images/theboys.jpg',
      category: 'Comic-book',
      price: 2.99,
      editor: 'WildStorm',
      authors: 'Garth Ennis, Darick Robertson',
      rating: 4.0,
      numReviews: 10,
      countInStock: 0,
      description:
        'The dark new series by Garth Ennis and Darick Robertson heats up as Wee Hughie gets his first taste of action with the Boys when Butcher throws him into the deep end. Meanwhile, meet the planet`s mightiest heroes, The Seven, and the young superheroine who would join them.',
    },
    {
      name: 'HIT MONKEY #1',
      slug: 'hit-monkey-1',
      images: '/images/monkey.jpeg',
      category: 'Comic-book',
      price: 1.99,
      editor: 'MARVEL',
      authors: 'Daniel Way, Dalibor Talajic',
      rating: 3.3,
      numReviews: 2,
      countInStock: 7,
      description:
        '"The Legend of Hit-Monkey" A troubled soul, set upon a path of vengeance he does not understand. An assassin without equal, trained in the most secret of killing techniques. A monkey,with a gun. Bear witness as the legend is born. Hit-Monkey.',
    },
    {
      name: 'BATMAN: DARK KNIGHT RETURNS',
      slug: 'batman-dark-knight-returns',
      images: '/images/batman.jpeg',
      category: 'Graphic Novel',
      price: 34.99,
      editor: 'DCcomics',
      authors: 'Frank Miller',
      rating: 4.2,
      numReviews: 101,
      countInStock: 110,
      description:
        'For the first time, DC Comics collects Frank Miller’s unforgettable Dark Knight epic in black and white! It is ten years after an aging Batman has retired, and Gotham City has sunk into decadence and lawlessness. Now, as his city needs him most, the Dark Knight returns in a blaze of glory. Joined by Carrie Kelly, a teenaged Robin, Batman takes to the streets to end the threat of the mutant gangs that have overrun the city. And after facing off against The Joker and Two-Face for the final time, Batman finds himself in mortal combat with his former ally, Superman, in a battle that only one will survive.',
    },
    {
      name: 'CHAS - THE KNOWLEDGE #4',
      slug: 'chas-the-knowledge4',
      images: '/images/chas.jpeg',
      category: 'Comic-book',
      price: 2.99,
      editor: 'Vertigo',
      authors: '',
      rating: 4.0,
      numReviews: 14,
      countInStock: 40,
      description:
        'Red vs. Blue. The demon possessing Chas`s would-be protégé, Nicky, has unlocked the secrets of "The Knowledge," and now it`s looking to rip the soul right out of London. And where better to start than a football match between two of the city`s most heated rivals? The ensuing chaos creates a moment of decision in the life of Chas.',
    },
    {
      name: 'SUPERMAN #37',
      slug: 'superman37',
      images: '/images/superman.jpeg',
      category: 'Comic-book',
      price: 3.99,
      editor: 'DCcomics',
      authors: 'Geoff Johns, John Romita JR',
      rating: 4.0,
      numReviews: 91,
      countInStock: 910,
      description:
        'Can there be peace and good will toward people without a price? Geoff Johns and John Romita Jr. serve up some holiday shocks as they answer this question and more in this the penultimate chapter of “MEN OF TOMORROW”! And be warned – some significant changes are in store for the Man of Steel to ring in the New Year! This issue is also offered as a combo pack edition with a redemption code for a digital download of this issue.',
    },
  ],
};
export default data;
